export const Seniors = [
  {
    id: 1,
    name: "Vikash Kumar",
    college: "IIT Kharagpur",
    Batch: 2020,
    category: "IIT",
    Mobile: 9800642111,
    email: "krvkash3@gmail.com",
  },
  {
    id: 2,
    name: "Govind Kumar",
    college: "NIT Surathkal",
    Batch: 2020,
    category: "NIT",
    Mobile: 8970310885,
    email: "govindnath.nitk@gmail.com",
  },
  {
    id: 3,
    name: "Kanhaiya Lal",
    college: "NIT Trichy",
    Batch: 2020,
    category: "NIT",
    Mobile: 8235036219,
    email: "kanhaiya.nit@gmail.com",
  },
  {
    id: 4,
    name: "Kedar Nath",
    college: "IIT Guwahati",
    Batch: 2021,
    category: "IIT",
    Mobile: 8434717170,
    email: "kena@gmail.com",
  },
  {
    id: 5,
    name: "Sumit Kumar",
    college: "IIT Kanpur",
    Batch: 2021,
    category: "IIT",
    Mobile: 8651556141,
    email: "kumarsmt88@gmail.com",
  },
];
